# Travis

os: osx
osx_image: xcode11.3
language: objective-c

branches:
  only:
    - develop

cache:
  directories:
  - Carthage

before_install:
  - export IOS_SIMULATOR_DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=13.3"

install:
- brew install carthage || true
- brew outdated carthage || brew upgrade carthage
- travis_wait 30 carthage bootstrap --platform iOS --cache-builds

before_script:
  - set -o pipefail

script:
  - travis_retry xcodebuild test -scheme MobileOrg -destination "$IOS_SIMULATOR_DESTINATION" | xcpretty -c

notifications:
  irc: 
    "irc.freenode.net#mobileorg"

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/adf14670ff7dc3b1fc67
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
